import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Monoton, Anta } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { BackgroundMusic } from "./_components/BackgroundMusic";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const monoton = Monoton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-monoton",
});

const anta = Anta({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anta",
});

import { UnifiedBackground } from "./_components/UnifiedBackground";

import { ScaledContainer } from "~/components/ScaledContainer";
import { AuthProvider } from "./_components/auth-provider";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} ${monoton.variable} ${anta.variable}`}>
      <body className="font-[family-name:var(--font-anta)] bg-black w-screen h-screen overflow-hidden flex items-center justify-center">
        <ScaledContainer>
          <UnifiedBackground />
          <BackgroundMusic />
          <AuthProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </AuthProvider>
        </ScaledContainer>
      </body>
    </html>
  );
}
